### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by yosungho** [yosungho/LineTR#1]
We plan to release LineTR code in few weeks. Please subscribe to this issue if you hope to be notified.

**Comment by alighofrani95** [comment]
subscribe ...

**Comment by ducha-aiki** [comment]
Hi,

May I ask about the license you are going to release the code & weights?

**Comment by yosungho** [comment]
Since I am reusing SuperPoint and SuperGlue, it will follow the research only & non-commercial use license.

**Comment by yosungho** [comment]
> Hi,
> 
> May I ask about the license you are going to release the code & weights?

Since I am reusing SuperPoint and SuperGlue, it will follow the research only & non-commercial use license.

**Comment by 812985728** [comment]
subscribe

**Comment by QinZiwen** [comment]
subscribe

**Comment by zubairahmed-ai** [comment]
subscribe

**Comment by yosungho** [comment]
The LineTR is just released. Please have a try it in your environment. Thank you-! :)
