### ISSUE TITLE
How to test with the trained model on my own dataset?

### ISSUE THREAD

**Issue by jarvishou829** [yosungho/LineTR#12]
Hi, thanks for your great work. I wonder that how to test the model trained on my own dataset. I find that the match_line_pairs.py load superpoint model and linetr model but not my model_best.pth.tar? So how could I use it to infer.

**Comment by yosungho** [comment]
Hi, there. You can see the LineTR loading a pre-trained weight at line_transformer.py. you can switch the path to your own weight file. https://github.com/yosungho/LineTR/blob/main/models/line_transformer.py#L221
