### ISSUE TITLE
Why did I encounter the following error when running build_homography_dataset.py？

### ISSUE THREAD

**Issue by ZhHaoH** [yosungho/LineTR#13]
Hi, I want to ask why did I encounter the following error when running build_homography_dataset.py？
Traceback (most recent call last):
  File "/dataloaders/build_homography_dataset.py", line 324, in <module>
    main()
  File "/dataloaders/build_homography_dataset.py", line 318, in main
    dataset.__getitem__(iter, idx)
  File "/dataloaders/build_homography_dataset.py", line 222, in __getitem__
    klines0 = conv_fixed_size(klines0, self.conf, func_token=line_tokenizer, pred_sp=pred0)
  File "/dataloaders/utils/util_lines.py", line 721, in conv_fixed_size
    klines_np = {k: v[0].cpu().numpy() for k, v in klines.items()}
  File "/dataloaders/utils/util_lines.py", line 721, in <dictcomp>
    klines_np = {k: v[0].cpu().numpy() for k, v in klines.items()}
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by ZhHaoH** [comment]
After I had created over 2000 images, suddenly there was an issue with one image during the generation process

**Comment by yosungho** [comment]
I apologize for the delay in my response. Yes, there might be some issues, particularly when a line segment isn't recognized in an image. Kindly remove any poor-quality samples from your dataset. I'll make some corrections when I find the time.

**Comment by ZhHaoH** [comment]
Thank you, I did use the method of removing poor quality data, and I found that there were broken images in my downloaded Oxford and Paris dataset itself
