### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'tell'

### ISSUE THREAD

**Issue by Adblu** [yosungho/LineTR#2]
When running match_line_pairs.py such error occurs.

**Comment by yosungho** [comment]
The error seems to be related to python and pytorch versions. Which version of those do you use? I have tested it with python 3.6.9 and pytorch 1.8 and 1.9.

**Comment by yosungho** [comment]
Have you tried other Python / Pytorch versions? If your problem is solved, please close the issue. Thank you-
