### ISSUE TITLE
code of line-based homography estimation

### ISSUE THREAD

**Issue by EchoTHChen** [yosungho/LineTR#3]
Hi! I'm very interested in your work because recently I want to use line descriptors for homography estimation. I noticed that you implemented the code of the paper _"Combining line and point correspondences for homography estimation"_. But I did not find out the code of that part in this repository for homography estimation. Could you provide the code for that part?

**Comment by ChrisLLLLL** [comment]
> Yes, I did not upload the homography estimation code here. I am sending you the raw code by email, as we talked about in the email.

Hello, Could you send me this homography estimation code？ I have sent you an email.Thank you!

**Comment by jia199903** [comment]
@EchoTHChen ，hello,Could you provide the code that the author send you the raw code about homography estimation?thank you very much,I expect your reply
