### ISSUE TITLE
Homograph AUC

### ISSUE THREAD

**Issue by Zhuyawen7** [yosungho/LineTR#8]
Hi,
How did you get the result of Homography Auc? When I watched superglue i know how to ask AUC for points, but not how to ask for AUC for lines

**Comment by yosungho** [comment]
Hello Zhuyawen, 
I computed the average reprojection errors of the four image corners and report the area under the cumulative error curve (AUC) at the thresholds (5, 10, and, 20 pixels). Please refer to the paper for more details.
